title: Dumbdown Blog
author:
  twitter: orph
  name: orph
  url: https://github.com/orph
social:
  name: FIXME
  links:
    - FIXME
twitter:
  username: FIXME
facebook:
  publisher: FIXME

description_no_title: FIXME 
